[build]
  publish = "dist"  # Ensure this matches your build output directory
  command = "npm run build"

[[headers]]
  for = "*.js"
  for = "*.ts"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css"
