[build]
  publish = "dist"  # Ajusta si tu carpeta de salida es diferente
  command = "npm run build"

[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html"
